### ISSUE TITLE
是否引入更多依赖

### ISSUE THREAD

**Issue by 3attaE** [treeman-zhou/XKP-API#2]
**[lombok插件](https://projectlombok.org/)**
让代码更简洁

[Mybatis-plus](https://mybatis.plus/)
简化开发基础 CRUD

**Comment by treeman-zhou** [comment]
- We are going to add "Lombok" in next edition, you can also submit your code.
- "MyBatis-Plus" is a powerful plugin, but I'm sorry that we will not use it.
